FROM node:14-alpine

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://127.0.0.1:8000


RUN npm install && \
    npm run build && \
    npm install -g serve

USER node

CMD ["serve",  "-s",  "-l" , "5000" , "build"]
