version: '3.3'

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000

  backend:
    image: backend
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis-service
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PASSWORD=supersecret
    networks:
      - database-network

  redis:
    image: redis
    container_name: redis-service
    networks:
      - database-network

  postgres-db:
    image: postgres
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - database-network
    environment:
      - POSTGRES_PASSWORD=supersecret

networks:
  database-network:
  
volumes:
  postgres-data:

