FROM node:14-alpine AS builder

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://127.0.0.1:8000


RUN npm install && \
    npm run build


FROM nginx:alpine
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

CMD ["nginx",  "-g",  "daemon off;"]
