FROM ubuntu:18.04

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://127.0.0.1:8000

#RUN useradd -m node

RUN apt-get update && apt-get -y upgrade && \
    apt-get install -y ca-certificates curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/* && \
    npm install && \
    npm run build && \
    npm install -g serve && \
    useradd -m node && chown node /usr/src/app

USER node

CMD ["serve",  "-s",  "-l",  "5000",  "build"]
