FROM golang:latest

EXPOSE 8000

WORKDIR /usr/src/app

COPY . .

ENV PORT=8000

ENV REQUEST_ORIGIN=http://127.0.0.1:5000

RUN useradd -m go

RUN chown go /usr/src/app

USER go

RUN go build

CMD ./server

