FROM node:lts

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://127.0.0.1:8000

#RUN useradd -m node

RUN chown -R node /usr/src/app
RUN chown -R node /usr/local/lib/node_modules/

USER node

RUN npm install

RUN npm run build

RUN npm install serve

CMD /usr/src/app/node_modules/serve/bin/serve.js -s -l 5000 build
